### ISSUE TITLE
Module fails validation for Foundry v10

### ISSUE THREAD

**Issue by Eagle0600** [Ironxxx/pf1ultimatepsionics#6]
`[pf1ultimatepsionics] Metadata validation failed for module "pf1ultimatepsionics": Module Model Validation Errors
[Module.packs]: Model Validation Errors
The Compendium pack "psionic-items" of the "Item" type must declare the "system" upon which it depends`

**Comment by Ironxxx** [comment]
Thank you for letting me know, this is unlikely to get looked at any time soon I'm afraid.

**Comment by Eagle0600** [comment]
If it helps, I know the fix. It's a single line in the module.json: Insert `"system": "pf1",` at line 45.

**Comment by Ironxxx** [comment]
Cheers, I've added that in. I'm not updating to V10 for some time so let me know it it's ok.

Thanks again.

**Comment by Eagle0600** [comment]
It works, in so far as it passes validation and doesn't throw any errors. There are some problems with the items themselves (the power descriptions don't show up), which presumably are due to a change in the data format between versions, but that would be a much more extensive problem to fix and more importantly would break backwards compatibility. I can work around them.

Thank you for your time.
